Bookworm network man
flightaware/piaware-support pull request #4
Opened 2024-12-04 16:26 UTC by nikeflight

1. Add piaware_config.py to read from piaware config folders.
2. Add script to generate NetworkManager file
3. Edit piaware-support.install to point to new bookworm files.

2025-01-01 12:57 UTC, eric1tran requested changes
Can you add some file descriptions / comments to the new python scripts? I think an explanation that it's a rewrite of https://github.com/flightaware/piaware/blob/master/package/fa_piaware_config.tcl as a python package and how it works would be useful

2025-01-01 12:57 UTC, eric1tran commented on scripts/piaware_config.py
> +PIAWARE_CONFIG_ENUMS["network_config_style"] = ["sdr", "stratuxv3", "other", "none"]
copy paste error? The values for these should be the [Debian OS names](https://github.com/flightaware/piaware/blob/master/package/fa_piaware_config.tcl#L61). 

[generate-network-config](https://github.com/flightaware/piaware-support/blob/master/scripts/generate-network-config#L418) uses this setting to determine how to generate the config. Is this setting now obsolete in Bookworm since we have a separate generate-network-config-bookworm?

2025-01-01 12:57 UTC, eric1tran commented on scripts/piaware_config.py
> +    def get(self, setting_key: str) -> any:
Is there support for setting a config?

2025-01-02 16:12 UTC, nikeflight commented on scripts/piaware_config.py
> +    def get(self, setting_key: str) -> any:
There is in the original TCL config.

I remember Oliver and I had decided that we not implement setting for now. 
Since we're doing a large re-write and these values don't change often.

2025-01-10 13:26 UTC, eric1tran requested changes

2025-01-10 13:26 UTC, eric1tran commented on scripts/piaware_config.py
> +        self.settings["force-mac-address"] = MetadataSettings(setting_type="MAC")
This should be `force-macaddress`

2025-01-10 13:26 UTC, eric1tran commented on scripts/piaware_config.py
> +        self.settings["wireless-nameserver"] = MetadataSettings(default = ["8.8.8.8", "8.8.4.4"], sdonly=True, network=True)
wireless-nameservers

2025-01-10 13:39 UTC, eric1tran requested changes

2025-01-10 13:39 UTC, eric1tran commented on tests/test_piaware_config.py
> +        assert testm.convert_value("force-mac-address", "01:23:45:67:89:AB") == "01:23:45:67:89:AB"
force-macaddress

2025-01-10 13:39 UTC, eric1tran commented on package/helpers/piaware-restart-network-bookworm
Should add this file to package/helpers/Makefile

2025-01-10 19:28 UTC, merged